- name: Install Jenkins on Amazon Linux
  hosts: all
  become: yes

  tasks:
    - name: Ensure Java is installed
      become: yes
      yum:
        name: java
        state: present

    - name: Add Jenkins Repository
      become: yes
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: http://pkg.jenkins.io/redhat
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io-2023.key
        state: present

    - name: Install Jenkins
      become: yes
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins Service
      become: yes
      systemd:
        name: jenkins
        state: started
        enabled: yes